#USANDO UNO DE LOS OPERADORES DE COMPARACION DE PYTHON ESCRIBE UN PROGRAMA SIMPLE DE DOS LINEAS QUE TOME EL PARAMETRO
#N COMO ENTRADA, QUE ES UN ENTERO, E IMPRIME FALSE SIN N ES EL MENOR QUE 100, Y TRUE SI N ES MAYOR O IGUAL QUE 100
a=int(input("Enter a number"))
print(a>=100)